-- Check if the required tables and columns exist
SELECT 
    TABLE_NAME,
    COLUMN_NAME,
    DATA_TYPE,
    IS_NULLABLE,
    COLUMN_KEY
FROM INFORMATION_SCHEMA.COLUMNS 
WHERE TABLE_SCHEMA = 'vocalyx' 
AND TABLE_NAME IN ('users', 'custom_roles', 'role_permissions')
ORDER BY TABLE_NAME, ORDINAL_POSITION;

-- Check foreign key constraints
SELECT 
    CONSTRAINT_NAME,
    TABLE_NAME,
    COLUMN_NAME,
    REFERENCED_TABLE_NAME,
    REFERENCED_COLUMN_NAME
FROM INFORMATION_SCHEMA.KEY_COLUMN_USAGE 
WHERE TABLE_SCHEMA = 'vocalyx' 
AND REFERENCED_TABLE_NAME IS NOT NULL
AND TABLE_NAME IN ('users', 'custom_roles', 'role_permissions');
